services:
  go-app:
    image: golang:1.22
    ports:
      - "3000:3000"
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - GOPROXY=https://proxy.golang.org,direct
      - PORT=3000
    working_dir: /go/src/
    volumes:
      - ./src:/go/src
    command:
     /bin/sh -c "
      openssl genpkey -algorithm RSA -out root-ca.key && \
      cp ./root-ca.key ../../usr/share/ca-certificates/root-ca.crt && \
      cp ./root-ca.key ../../usr/local/share/ca-certificates/root-ca.pem && \
      update-ca-certificates && \
      go mod tidy && \ 
      go build -o linux/app && GOOS=windows GOARCH=amd64 go build -o win/app.exe \ &&
      chmod +x ./linux/app && \ 
      ./linux/app
      " 