
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER root
WORKDIR /app


FROM  mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src


COPY ["./src/src.csproj" , "."]
RUN dotnet restore "./src.csproj"
COPY ./src/*.cs ./src/*.csproj ./src/**/*.proj ./src/**/*.json ./src/**/*.xml ./src/**/*.config ./src/**/*.g ./


RUN dotnet build "src.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
RUN dotnet publish "src.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false


FROM base AS final 
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet" , "./bin/Debug/net8.0/src.dll" ]
